[workspace]
members = [
    ".", # The main package
    "crates/shared",
    "crates/artifact",
    "crates/iam",
    "crates/repository",
    "crates/supply-chain",
    "crates/search",
    "crates/security",
    "crates/analytics",
    "crates/distribution",
    "crates/infra-mongo",
    "crates/organization"
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
bytes = "1"
time = { version = "0.3", features = ["serde"] }
bollard = "0.19.2"
anyhow = { version = "^1.0" }
async-trait = { version = "0.1.89" }
aws-config = "1.8.6"
aws-sdk-s3 = "1.104.0"
aws-types = { version = "1.3.8" }
aws-credential-types = { version = "1.2.6" }
axum = { version = "0.8.4", features = ["macros"] } # Using latest stable
base64 = "^0.22"
cedar-policy = "4.5.1"
chrono = { version = "^0.4", features = ["serde"] }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
hex = "0.4"
hyper = { version = "1", features = ["full"] }
jsonwebtoken = "^9.3"
mime = "0.3"
mongodb = "3.3.0"
lapin = { version = "3.4.0" }
redis = { version = "0.32.5", features = ["tokio-comp"] }
reqwest = { version = "0.12.4", features = ["json"] }
ring = "^0.17"
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
sha2 = { version = "^0.10" }
ed25519-dalek = "2.0"
testcontainers = { version = "0.25.0" }
testcontainers-modules = { version = "0.13.0" }
thiserror = { version = "2.0.16" }
tokio = { version = "^1.38", features = ["full"] }
tokio-util = { version = "0.7" }
tracing = { version = "^0.1" }
uuid = { version = "1.8.0", features = ["v4", "serde"] } # Using latest stable
mockall = "0.11.0"
wiremock = "0.5"

# Additional dependencies for centralized version management
url = "2.5.0"
tracing-subscriber = "0.3.20"
tracing-test = "0.2.5"
regex = "1.0"
tower = { version = "0.5", features = ["util"] }
infer = "0.19.0"

[package]
name = "hodei-artifacts-api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "hodei_artifacts_api"
path = "src/lib.rs"

[[bin]]
name = "hodei-artifacts-api"
path = "src/main.rs"

[dependencies]
# Point to the new crates
shared = { path = "crates/shared" }
artifact = { path = "crates/artifact" }
iam = { path = "crates/iam" }
repository = { path = "crates/repository" }
"supply-chain" = { path = "crates/supply-chain" }
search = { path = "crates/search" }
security = { path = "crates/security" }
analytics = { path = "crates/analytics" }
distribution = { path = "crates/distribution" }
infra-mongo = { path = "crates/infra-mongo" }
organization = { path = "crates/organization" }


# Core
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["multipart"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tower = { workspace = true }
chrono = { workspace = true }
# Actualizamos hyper a la rama 1.x (compatible con axum 0.7 / hyper 1) usando caret para parches.
hyper = { version = "1.7.0", features = ["server"] }
cedar-policy.workspace = true
aws-sdk-s3.workspace = true
aws-config.workspace = true