[workspace]
members = [
    ".",
    "crates/shared",
    "crates/artifact",
    "crates/iam",
    "crates/repository",
    "crates/supply-chain",
    "crates/search",
    "crates/security",
    "crates/analytics",
    "crates/integration",
    "crates/distribution",
    "crates/infra-mongo"
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[package]
name = "hodei-artifacts-api"
version = "0.1.0"
edition = "2024"

[lib]
name = "hodei_artifacts_api"
path = "src/lib.rs"

[[bin]]
name = "hodei-artifacts-api"
path = "src/main.rs"

[dependencies]
shared = { path = "crates/shared" }
artifact = { path = "crates/artifact" }
iam = { path = "crates/iam" }
repository = { path = "crates/repository" }
"supply-chain" = { path = "crates/supply-chain" }
search = { path = "crates/search" }
security = { path = "crates/security" }
analytics = { path = "crates/analytics" }
integration = { path = "crates/integration" }
distribution = { path = "crates/distribution" }
infra-mongo = { path = "crates/infra-mongo" }

# Core
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["multipart"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
# Actualizamos hyper a la rama 1.x (compatible con axum 0.7 / hyper 1) usando caret para parches.
hyper = { version = "1", features = ["server"] }

[workspace.dependencies]
hyper = { version = "1", features = ["full"] }
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { version = "^1.38", features = ["full"] }
axum = { version = "0.8.4" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
tracing = { version = "^0.1" }
anyhow = { version = "^1.0" }
thiserror = { version = "2.0.16" }
uuid = { version = "^1.0", features = ["v4", "serde"] }
chrono = { version = "^0.4", features = ["serde"] }
async-trait = { version = "^0.1" }
futures = { version = "0.3" }

# Infra opcional inicial (caret para últimas releases compatibles)
mongodb = "3.2.5"
redis = { version = "0.32.5", features = ["tokio-comp"] }
aws-config = "^1.0"
aws-sdk-s3 = "^1.0"
rdkafka = { version = "0.38.0", features = ["cmake-build"] }
cedar-policy = "4.5.1"
jsonwebtoken = "^9.3"
ring = "^0.17"
sha2 = "^0.10"
# TEST-TC2: dependencia común para tests de integración con contenedores efímeros
testcontainers = { version = "0.24.0", default-features = false }
testcontainers-modules = { version = "0.12.1" }
