[workspace]
members = [
    ".",
    "crates/shared",
    "crates/artifact",
    "crates/iam",
    "crates/repository",
    "crates/supply-chain",
    "crates/search",
    "crates/security",
    "crates/analytics",
    "crates/integration",
    "crates/distribution"
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[package]
name = "hodei-artifacts-api"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "crates/shared" }
artifact = { path = "crates/artifact" }
iam = { path = "crates/iam" }
repository = { path = "crates/repository" }
"supply-chain" = { path = "crates/supply-chain" }
search = { path = "crates/search" }
security = { path = "crates/security" }
analytics = { path = "crates/analytics" }
integration = { path = "crates/integration" }
distribution = { path = "crates/distribution" }

# Core
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["multipart"] }
serde = { workspace = true }
serde_json = "1.0"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[workspace.dependencies]
tokio = { version = "1.38", features = ["full"] }
axum = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.8", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

# Infra opcional inicial
mongodb = "2.8"
redis = { version = "0.24", features = ["tokio-comp"] }
aws-sdk-s3 = "1.0"
rdkafka = { version = "0.36", features = ["cmake-build"] }
cedar-policy = "3.0"
jsonwebtoken = "9.3"
ring = "0.17"
sha2 = "0.10"
