[package]
name = "repository"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true } # As defined in domain model
cedar-policy = { workspace = true }
shared = { path = "../shared" }