[package]
name = "repository"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
url = { version = "2.5.0" } # As defined in domain model
cedar-policy = { workspace = true }
shared = { path = "../shared" }