[package]
name = "supply-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
cedar-policy = { workspace = true }
shared = { path = "../shared" }