use serde::{Deserialize, Serialize};

/// Acciones soportadas por el sistema para evaluación de políticas.
/// Basado en el diagrama Mermaid `Action`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Action {
    CreateUser,
    ReadUser,
    UpdateUser,
    DeleteUser,
    ManagePolicies,
    ManageApiKeys,
    CreateOrganization,
    ManageOrganization,
    ManageTeams,
    ManageMemberships,
    CreateRepository,
    ReadRepository,
    WriteRepository,
    DeleteRepository,
    ReadArtifact,
    WriteArtifact,
    DeleteArtifact,
    ManageMetadata,
    ReadConfiguration,
    WriteConfiguration,
    ManageConfigVersions,
    PublishEvent,
    ReadEvent,
    ManageEventStreams,
    ManageSubscriptions,
    ReadMetrics,
    CreateDashboard,
    ManageDashboards,
    GenerateReports,
    ManageAlerts,
    CreateAttestation,
    ReadAttestation,
    ManageKeys,
    RunScans,
    ReadScanResults,
    ManageProvenance,
    ManageStorage,
    ReadStorage,
    WriteStorage,
    CreateMonitor,
    ReadMonitor,
    ManageMonitors,
    ReadLogs,
    AdminAccess,
    SystemAccess,
}
