[package]
name = "policies"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
shared = { path = "../shared" }
chrono = { workspace = true }
serde_json = { workspace = true }
