[server]
host = "0.0.0.0"
port = 3000
request_timeout_secs = 30
max_body_size = 10485760  # 10MB

[database]
db_type = "rocksdb"
namespace = "hodei"
database = "artifacts"
pool_size = 10

[rocksdb]
path = "./data/hodei.rocksdb"
create_if_missing = true
compression = true
max_open_files = 1000
write_buffer_size = 67108864  # 64MB

[schema]
register_iam_on_startup = false
validate = true
storage_type = "rocksdb"

[logging]
level = "info"
format = "pretty"
include_timestamps = true
include_location = false
