[profile.default]
test-threads = "num-cpus"
slow-timeout = { period = "60s", terminate-after = 2 }
retries = 0
failure-output = "immediate"
success-output = "never"

[profile.ci]
retries = 2
slow-timeout = { period = "120s", terminate-after = 3 }
failure-output = "immediate-final"
success-output = "never"

[profile.quick]
test-threads = "num-cpus"
slow-timeout = { period = "30s" }
retries = 0
failure-output = "immediate"
success-output = "never"
