[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
cedar-policy = { workspace = true }
uuid = { workspace = true }