[package]
name = "distribution"
version = "0.1.0"
edition = "2024"
license = "MIT"
[dependencies]
shared = { path = "../shared" }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
